export function AboutView() {
  return (
    <div className="max-w-3xl mx-auto space-y-8 py-8">
      <div className="space-y-4 text-slate-600 leading-relaxed text-base">
        <h2 className="text-3xl font-bold text-slate-900 mb-6 tracking-tight">About Hydroponic Planning Hub</h2>
        
        <p>
          Hydroponic is part of the <strong>Rural Utility Cost</strong> ecosystem. It serves as a specialized economics, nutrient, and production planning hub for indoor growers, CEA operators, and agricultural managers.
        </p>

        <p>
          Our mission is to help growers estimate startup costs, nutrient needs, electricity use, crop profitability, ROI, and make operating decisions for hydroponic and controlled growing systems. Our tools support vertical farming, NFT, DWC, ebb-and-flow, and standard greenhouse setups.
        </p>

        <p>
          Whether analyzing capital expenditures for a new build or modeling the monthly electricity costs of a vertical rack system, these calculators provide baseline metrics designed to integrate naturally with broader rural utility modeling.
        </p>

        <div className="pt-8 mt-8 border-t border-slate-200">
          <h3 className="text-xl font-semibold text-slate-900 mb-4">Core Principles</h3>
          <ul className="list-disc pl-5 space-y-2">
            <li>Data-First clarity over promotional flash.</li>
            <li>Practical operating estimates designed for real-world viability checks.</li>
            <li>Direct integration with Rural Utility Cost operational philosophies.</li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export function LegalView() {
  return (
    <div className="max-w-3xl mx-auto space-y-8 py-8">
      <div className="space-y-4 text-slate-600 leading-relaxed text-base">
        <h2 className="text-3xl font-bold text-slate-900 mb-6 tracking-tight">Legal & Disclaimers</h2>
        
        <div className="bg-amber-50 border-l-4 border-amber-500 p-5 rounded-r-lg text-amber-900 mb-8 font-medium">
          The models and outputs generated by Hydroponic within the Rural Utility Cost platform are estimates only.
        </div>

        <p>
          Nutrient needs, crop performance, energy prices, and yields are subject to substantial operational, environmental, and regional variation.
        </p>
        
        <p>
          Information provided here does not constitute, nor replace, professional agronomy, engineering, legal, or financial advice. Users should verify all important agricultural business decisions independently with local extension agents, certified agronomists, or specialized financial advisors.
        </p>
      </div>
    </div>
  );
}
