import React, { useState } from 'react';

export function AboutView() {
  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="bg-white rounded-lg border border-slate-200 p-5 shadow-sm">
        <h2 className="text-2xl font-bold text-slate-900">About Hydroponic Planning Hub</h2>
        <p className="text-[10px] font-bold uppercase tracking-wider text-slate-500 mt-1">Part of the Rural Utility Cost Ecosystem</p>
      </div>

      <div className="bg-white rounded-lg border border-slate-200 p-6 shadow-sm space-y-4 text-sm text-slate-600 leading-relaxed font-medium">
        <p>
          Hydroponic is part of the <strong className="text-slate-800">Rural Utility Cost</strong> ecosystem. It serves as a specialized economics, nutrient, and production planning hub for indoor growers, CEA operators, and agricultural managers.
        </p>

        <p>
          Our mission is to help growers estimate startup costs, nutrient needs, electricity use, crop profitability, ROI, and make operating decisions for hydroponic and controlled growing systems. Our tools support vertical farming, NFT, DWC, ebb-and-flow, and standard greenhouse setups.
        </p>

        <p>
          Whether analyzing capital expenditures for a new build or modeling the monthly electricity costs of a vertical rack system, these calculators provide baseline metrics designed to integrate naturally with broader rural utility modeling.
        </p>

        <div className="pt-6 mt-6 border-t border-slate-100">
          <h3 className="text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-4">Core Principles</h3>
          <ul className="list-disc pl-5 space-y-2 text-slate-600">
            <li><strong className="text-slate-700">Data-First:</strong> Clarity over promotional flash.</li>
            <li><strong className="text-slate-700">Practicality:</strong> Operating estimates designed for real-world viability checks.</li>
            <li><strong className="text-slate-700">Integration:</strong> Direct integration with Rural Utility Cost operational philosophies.</li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export function LegalView() {
  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="bg-white rounded-lg border border-slate-200 p-5 shadow-sm">
        <h2 className="text-2xl font-bold text-slate-900">Legal & Disclaimers</h2>
        <p className="text-[10px] font-bold uppercase tracking-wider text-slate-500 mt-1">Important Usage Information</p>
      </div>

      <div className="bg-white rounded-lg border border-slate-200 p-6 shadow-sm space-y-5 text-sm text-slate-600 leading-relaxed font-medium">
        <div className="bg-blue-50 border border-blue-100 p-4 rounded text-blue-900">
          <h4 className="text-[10px] font-bold text-blue-600 uppercase tracking-widest mb-2">Estimate Only</h4>
          <p className="text-sm">The models and outputs generated by Hydroponic within the Rural Utility Cost platform are estimates only.</p>
        </div>

        <p>
          Nutrient needs, crop performance, energy prices, and yields are subject to substantial operational, environmental, and regional variation.
        </p>
        
        <p>
          Information provided here does not constitute, nor replace, professional agronomy, engineering, legal, or financial advice. Users should verify all important agricultural business decisions independently with local extension agents, certified agronomists, or specialized financial advisors.
        </p>
      </div>
    </div>
  );
}

export function ContactView() {
  const [status, setStatus] = useState<string>('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setStatus('Message sent successfully. We will be in touch soon.');
    if (typeof window !== 'undefined' && typeof (window as any).gtag === 'function') {
      (window as any).gtag('event', 'generate_lead', {
        event_category: 'contact',
        event_label: 'contact_form_submit'
      });
    }
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="bg-white rounded-lg border border-slate-200 p-5 shadow-sm">
        <h2 className="text-2xl font-bold text-slate-900">Contact Us</h2>
        <p className="text-[10px] font-bold uppercase tracking-wider text-slate-500 mt-1">Reach Out to Rural Utility Cost</p>
      </div>

      <div className="bg-white rounded-lg border border-slate-200 p-6 shadow-sm">
        {status ? (
          <div className="bg-emerald-50 border border-emerald-200 text-emerald-800 p-4 rounded text-sm font-medium">
            {status}
          </div>
        ) : (
          <form className="space-y-4" onSubmit={handleSubmit}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label htmlFor="name" className="text-[10px] uppercase font-bold text-slate-500 mb-1 block">Full Name</label>
                <input id="name" type="text" required className="w-full text-sm border-slate-200 rounded border bg-slate-50 p-3 font-medium focus:outline-none focus:ring-2 focus:ring-emerald-500" placeholder="John Doe" />
              </div>
              <div>
                <label htmlFor="email" className="text-[10px] uppercase font-bold text-slate-500 mb-1 block">Email Address</label>
                <input id="email" type="email" required className="w-full text-sm border-slate-200 rounded border bg-slate-50 p-3 font-medium focus:outline-none focus:ring-2 focus:ring-emerald-500" placeholder="john@example.com" />
              </div>
            </div>
            <div>
              <label htmlFor="subject" className="text-[10px] uppercase font-bold text-slate-500 mb-1 block">Subject</label>
              <select id="subject" required className="w-full text-sm border-slate-200 rounded border bg-slate-50 p-3 font-medium focus:outline-none focus:ring-2 focus:ring-emerald-500">
                <option value="">Select a topic...</option>
                <option value="support">Technical Support</option>
                <option value="feedback">Tool Feedback</option>
                <option value="business">Business Inquiry</option>
              </select>
            </div>
            <div>
              <label htmlFor="message" className="text-[10px] uppercase font-bold text-slate-500 mb-1 block">Message</label>
              <textarea id="message" required rows={4} className="w-full text-sm border-slate-200 rounded border bg-slate-50 p-3 font-medium focus:outline-none focus:ring-2 focus:ring-emerald-500" placeholder="How can we help?"></textarea>
            </div>
            <button type="submit" className="w-full bg-slate-900 hover:bg-black text-white font-bold py-3 px-6 rounded min-h-[48px] shadow-sm uppercase tracking-wider text-xs transition-colors">
              Send Message
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
